### ISSUE TITLE
Server side game initialization (max one game)

### ISSUE THREAD

**Issue by BipedalMammalRescue** [cs130-w21/13#12]
## User Story
As a **player**, I would like **to find an opponent online** so that **I am paired with an opponent when I start a new game**.

## Detailed Description
Players can match an opponent and start game online. 

## Tasks
- [x] Research best multiplayer playing/debugging in Unity #57
- [ ] Server initialize game as per task

## Acceptance Criteria
- [x] Given **a new player enters matching pool and there is not already a running game**, then **the server waits for and finds another player in the pool to pair with the new player**
- [x] Given **there is a pair of players**, then **the server instantiates a new game by setting up connections and initializing stats for each pair**
