### ISSUE TITLE
Functional Client

### ISSUE THREAD

**Issue by ghuser1023** [cs130-w21/13#13]
## Epic
There should be a client that users interact with to play the game: users should be able to input commands, navigate menus, and perform all actions in the game world via buttons, dragging and dropping, text entry, and/or other methods within the game window itself.

## User Stories
- [x] Start Menu #1
- [x] Basic Server UI Functionality #2 
- [x] Rendering Players On-Screen #3 
- [x] Drag and Drop GUI #4
