### ISSUE TITLE
Game Design

### ISSUE THREAD

**Issue by ghuser1023** [cs130-w21/13#14]
## Epic
Create the rules and structure of the game.

## User Stories
- [x] Engaging Core Game Play #35 
- [x] Power Up Design #36 
- [x] Win Condition Design #38 
- [x] Map Design #37 
- [x] Find Game Sprites #46
- [x] Figure out top level UIUX #47
- [x] Finalize game design details with game testing and playing around #52
