### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by ghuser1023** [cs130-w21/13#15]
## Epic
Users should be able to play games with other users, interacting with each other through the agents in the game world. This should be handled by the clients on both ends via an external server, responsible for synchronizing game state and setting up games.

## User Stories
- [x] POC Client Communication with Server #7
- [x] Setup Continuous Integration #17 
- [x] Setup Continuous Deployment #10 
- [x] Server side game initialization (max one game) #12
- [x] Client side multiplayer game initialization #26 
- [x] Server side forward player/game updates (max one game) #32
- [x] Client shows player updates #11 
- [x] Server side support multiple games #34
