### ISSUE TITLE
Drag and Drop Coding

### ISSUE THREAD

**Issue by ashen-00** [cs130-w21/13#16]
## Epic
Players should be able to control their agents through a grid-like drag and drop UI with limited commands and limited spaces for commands. 

## User Stories
- [x] Command Board - Base Sprite #18
- [x] Command Board - Can Hold Commands #20
- [x] Command Board - Can Process Movement Commands #22 
- [x] Command Board - Can Process Action Commands #24
- [x] Command Board - Highlight When Running #25 
- [x] Command Blocks - Sprites #28 
- [x] Command Blocks - Visual Feedback #29
