### ISSUE TITLE
POC Client Communication with Server

### ISSUE THREAD

**Issue by reginawang3495** [cs130-w21/13#7]
## User Story
As a **player**, I would like **the game to connect to a server** so that **I can play online with other users**.

## Detailed Description
Startup a backend in Node.js with basic functionality and fill in README.md with basic commands so that it's easy for other software engineers to work on the backend as well. Also, decide on networking (sockets or requests) based on Unity networking capabilities + POC endpoint/socket in frontend and backend.

## Tasks
- [x] Setup backend #48
- [x] Test sockets
## Acceptance Criteria
- [x] Given **you run the command to start a server**, then **the server runs**
- [x] Given **server is started**, then **you can make a request to the the server successfully**
- [x] Given **server is started**, then **frontend and backend sockets connect**
- [x] Given **server is started**, then **frontend can send info to the backend and vice versa**
