### ISSUE TITLE
Execution Phase

### ISSUE THREAD

**Issue by ashen-00** [cs130-w21/13#8]
## Epic
During the "Execution Phase", player agents execute the code.

## User Stories
- [x] Command Board - Can Process Movement Commands #22 
- [x] Command Board - Can Process Action Commands #24 
- [x] Using Power Ups #9 
- [x] Calling Power Ups in Code #27 
- [x] Collision Handling #31
